CREATE TABLE IF NOT EXISTS stores (
    store_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name VARCHAR(150) NOT NULL,
    address VARCHAR(255) NOT NULL
);

INSERT INTO stores (store_id, store_name, address)
VALUES
    (1, 'NP Nilsson Testbutik Båstad', 'Testgatan 10, Båstad'),
    (2, 'NP Nilsson Testbutik Ängelholm', 'Demovägen 25, Ängelholm'),
    (3, 'NP Nilsson Testlager Helsingborg', 'Lagergatan 5, Helsingborg')
ON CONFLICT (store_id) DO NOTHING;

SELECT setval('stores_store_id_seq', (SELECT COALESCE(MAX(store_id), 1) FROM stores));

ALTER TABLE users ADD COLUMN IF NOT EXISTS store_id BIGINT REFERENCES stores(store_id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_users_store_id ON users(store_id);
