const { Pool } = require('pg');
const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');

const dbUser = process.env.SPRING_DATASOURCE_USERNAME || process.env.POSTGRES_USER || 'np_db_user';
const dbPassword = process.env.SPRING_DATASOURCE_PASSWORD || process.env.POSTGRES_PASSWORD || 'np_db_password';
const dbHost = process.env.POSTGRES_HOST || 'postgres';
const dbPort = process.env.POSTGRES_PORT || 5432;
const dbName = process.env.POSTGRES_DB || 'np_nilson';

const pool = new Pool({
    host: dbHost,
    port: Number(dbPort),
    database: dbName,
    user: dbUser,
    password: dbPassword,
});

async function initDatabase() {
    const client = await pool.connect();
    try {
        // Create stores table
        await client.query(`
            CREATE TABLE IF NOT EXISTS stores (
                store_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                store_name VARCHAR(150) NOT NULL,
                address VARCHAR(255) NOT NULL
            );
        `);

        // Seed fictional stores
        await client.query(`
            INSERT INTO stores (store_id, store_name, address)
            VALUES
                (1, 'NP Nilsson Testbutik Båstad', 'Testgatan 10, Båstad'),
                (2, 'NP Nilsson Testbutik Ängelholm', 'Demovägen 25, Ängelholm'),
                (3, 'NP Nilsson Testlager Helsingborg', 'Lagergatan 5, Helsingborg')
            ON CONFLICT (store_id) DO NOTHING;
        `);

        // Update identity sequence for store_id
        await client.query(`
            SELECT setval('stores_store_id_seq', (SELECT COALESCE(MAX(store_id), 1) FROM stores));
        `);

        // Create users table
        await client.query(`
            CREATE TABLE IF NOT EXISTS users (
                id UUID PRIMARY KEY,
                firstname VARCHAR(100) NOT NULL,
                lastname VARCHAR(100) NOT NULL,
                email VARCHAR(255) NOT NULL,
                password_hash VARCHAR(255) NOT NULL,
                role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'USER')),
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
        `);

        // Add store_id column to users table if not existing
        await client.query(`
            ALTER TABLE users ADD COLUMN IF NOT EXISTS store_id BIGINT REFERENCES stores(store_id) ON DELETE SET NULL;
        `);

        await client.query(`
            CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower ON users (LOWER(email));
        `);

        await client.query(`
            CREATE INDEX IF NOT EXISTS idx_users_store_id ON users(store_id);
        `);

        await client.query(`
            CREATE TABLE IF NOT EXISTS user_sessions (
                token VARCHAR(128) PRIMARY KEY,
                user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
                revoked BOOLEAN NOT NULL DEFAULT FALSE
            );
        `);

        await client.query(`
            CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions(user_id);
        `);

        await client.query(`
            CREATE INDEX IF NOT EXISTS idx_user_sessions_expires_at ON user_sessions(expires_at);
        `);

        // Seed admin users
        const adminEmail1 = process.env.SEED_ADMIN_EMAIL || 'admin@npnilsson.se';
        const adminEmail2 = 'admin@admin.com';
        const adminPassword = process.env.SEED_ADMIN_PASSWORD || 'AdminSecurePassword123!';
        const adminPasswordAlt = 'admin';
        const hashed1 = await bcrypt.hash(adminPassword, 10);
        const hashed2 = await bcrypt.hash(adminPasswordAlt, 10);

        const check1 = await client.query('SELECT id FROM users WHERE LOWER(email) = LOWER($1)', [adminEmail1]);
        if (check1.rows.length === 0) {
            await client.query(
                'INSERT INTO users (id, firstname, lastname, email, password_hash, role) VALUES ($1, $2, $3, $4, $5, $6)',
                [uuidv4(), 'NP', 'Admin', adminEmail1, hashed1, 'ADMIN']
            );
            console.log(`Seeded admin user: ${adminEmail1}`);
        }

        const check2 = await client.query('SELECT id FROM users WHERE LOWER(email) = LOWER($1)', [adminEmail2]);
        if (check2.rows.length === 0) {
            await client.query(
                'INSERT INTO users (id, firstname, lastname, email, password_hash, role) VALUES ($1, $2, $3, $4, $5, $6)',
                [uuidv4(), 'NP', 'Admin', adminEmail2, hashed2, 'ADMIN']
            );
            console.log(`Seeded admin user: ${adminEmail2}`);
        }

        // Seed test employee user (test@test.com / password: test, store_id: 1)
        const testEmail = 'test@test.com';
        const testPassword = 'test';
        const hashedTestPassword = await bcrypt.hash(testPassword, 10);

        const checkTest = await client.query('SELECT id, store_id FROM users WHERE LOWER(email) = LOWER($1)', [testEmail]);
        if (checkTest.rows.length === 0) {
            await client.query(
                'INSERT INTO users (id, firstname, lastname, email, password_hash, role, store_id) VALUES ($1, $2, $3, $4, $5, $6, $7)',
                [uuidv4(), 'Test', 'Employee', testEmail, hashedTestPassword, 'USER', 1]
            );
            console.log(`Seeded test employee user: ${testEmail} (store_id: 1)`);
        } else {
            // Ensure store_id is set to 1 for test employee
            await client.query(
                'UPDATE users SET store_id = 1 WHERE LOWER(email) = LOWER($1) AND (store_id IS NULL OR store_id != 1)',
                [testEmail]
            );
        }

        console.log('Database initialized and seeded successfully.');
    } catch (err) {
        console.error('Database initialization error:', err);
        throw err;
    } finally {
        client.release();
    }
}

module.exports = {
    pool,
    initDatabase,
};
